name: Python CI/CD

on:
  push:
    branches:
      - master   # Trigger when push is made to the master branch
  pull_request:
    branches:
      - master   # Trigger when a pull request is opened against the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Ubuntu

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Set up PostgreSQL
    - name: Set up PostgreSQL
      uses: shivammathur/setup-postgresql-action@v2
      with:
        postgresql-version: '13'
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: vacation_tracking

    # 5. Start PostgreSQL service
    - name: Start PostgreSQL
      run: |
        sudo service postgresql start

    # 6. Run tests
    - name: Run tests
      run: |
        pytest
