name: Python CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: vacation_tracking
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Python sürümünü netleştirdik

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # pytest'in yüklendiğini garanti altına al

      - name: Verify pytest installation
        run: |
          pytest --version  # pytest'in yüklendiğini kontrol et

      - name: Run tests
        env:
          DATABASE_URL: postgres://root:root@localhost:5432/vacation_tracking
        run: |
          # PostgreSQL hazır olana kadar bekle
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done
          # Test dosyalarını çalıştır
          pytest tests/  # Testlerin bulunduğu klasör
